//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIHost2host.PO_Services2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mi_os_poBinding", Namespace="urn:pertamina:po")]
    public partial class mi_os_poService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mi_os_poOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mi_os_poService() {
            this.Url = global::APIHost2host.Properties.Settings.Default.APIHost2host_PO_Services2_mi_os_poService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mi_os_poCompletedEventHandler mi_os_poCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("mt_po_response", Namespace="urn:pertamina:po")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("PO_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_po_responsePO_DETAILS[] mi_os_po([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:pertamina:po")] [System.Xml.Serialization.XmlArrayItemAttribute("PO_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] dt_po_requestPO_DETAILS[] mt_po_request) {
            object[] results = this.Invoke("mi_os_po", new object[] {
                        mt_po_request});
            return ((dt_po_responsePO_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void mi_os_poAsync(dt_po_requestPO_DETAILS[] mt_po_request) {
            this.mi_os_poAsync(mt_po_request, null);
        }
        
        /// <remarks/>
        public void mi_os_poAsync(dt_po_requestPO_DETAILS[] mt_po_request, object userState) {
            if ((this.mi_os_poOperationCompleted == null)) {
                this.mi_os_poOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmi_os_poOperationCompleted);
            }
            this.InvokeAsync("mi_os_po", new object[] {
                        mt_po_request}, this.mi_os_poOperationCompleted, userState);
        }
        
        private void Onmi_os_poOperationCompleted(object arg) {
            if ((this.mi_os_poCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mi_os_poCompleted(this, new mi_os_poCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILS {
        
        private string mANDTField;
        
        private string oPTYPEField;
        
        private string eBELN_EXTField;
        
        private string tESTRUNField;
        
        private string bSARTField;
        
        private string dELETE_INDField;
        
        private string aEDATField;
        
        private string bEDATField;
        
        private string lIFNRField;
        
        private string bUKRSField;
        
        private string wAERSField;
        
        private string eKORGField;
        
        private string wKURSField;
        
        private string eKGRPField;
        
        private string fRGKEField;
        
        private string zTERMField;
        
        private string iNCO1Field;
        
        private string iNCO2Field;
        
        private string zZMMTTYPEField;
        
        private string zZMMSHIPDATField;
        
        private string zZMMTYPEField;
        
        private string zZMMLCFINALField;
        
        private string zZMMBONDNOField;
        
        private string zZMMBANKLField;
        
        private string zZMMVLDSTARTField;
        
        private string zZMMVLDENDField;
        
        private string zZMMDLVTIMEField;
        
        private string zZMMUOTField;
        
        private string zZMMPARTALLOWField;
        
        private string zZMMAFEField;
        
        private string zZMMTKDNField;
        
        private string zZMMAUTHNAMEField;
        
        private string zZMMAUTHPOSField;
        
        private string zZMMPYMMTDField;
        
        private string rESIKOField;
        
        private string zZMMKOMODITASField;
        
        private string zZMMSTATUSPTField;
        
        private string zZMMPROCLISTField;
        
        private string zZMMBIDLISTField;
        
        private string zZIP2P_SUBBIDField;
        
        private string zZIP2P_OWNERESTField;
        
        private string zZIP2P_CURRField;
        
        private dt_po_requestPO_DETAILSVERSIONS vERSIONSField;
        
        private dt_po_requestPO_DETAILSHEADERTEXT[] hEADERTEXTField;
        
        private dt_po_requestPO_DETAILSPOADDRVENDOR pOADDRVENDORField;
        
        private dt_po_requestPO_DETAILSPOPARTNER[] pOPARTNERField;
        
        private dt_po_requestPO_DETAILSITEMS[] iTEMSField;
        
        private dt_po_requestPO_DETAILSLIMITS[] lIMITSField;
        
        private dt_po_requestPO_DETAILSSERVICE[] sERVICEField;
        
        private dt_po_requestPO_DETAILSPOSRVACCESSVALUES[] pOSRVACCESSVALUESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTYPE {
            get {
                return this.oPTYPEField;
            }
            set {
                this.oPTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN_EXT {
            get {
                return this.eBELN_EXTField;
            }
            set {
                this.eBELN_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TESTRUN {
            get {
                return this.tESTRUNField;
            }
            set {
                this.tESTRUNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AEDAT {
            get {
                return this.aEDATField;
            }
            set {
                this.aEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEDAT {
            get {
                return this.bEDATField;
            }
            set {
                this.bEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKORG {
            get {
                return this.eKORGField;
            }
            set {
                this.eKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WKURS {
            get {
                return this.wKURSField;
            }
            set {
                this.wKURSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FRGKE {
            get {
                return this.fRGKEField;
            }
            set {
                this.fRGKEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCO1 {
            get {
                return this.iNCO1Field;
            }
            set {
                this.iNCO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCO2 {
            get {
                return this.iNCO2Field;
            }
            set {
                this.iNCO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMTTYPE {
            get {
                return this.zZMMTTYPEField;
            }
            set {
                this.zZMMTTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMSHIPDAT {
            get {
                return this.zZMMSHIPDATField;
            }
            set {
                this.zZMMSHIPDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMTYPE {
            get {
                return this.zZMMTYPEField;
            }
            set {
                this.zZMMTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMLCFINAL {
            get {
                return this.zZMMLCFINALField;
            }
            set {
                this.zZMMLCFINALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMBONDNO {
            get {
                return this.zZMMBONDNOField;
            }
            set {
                this.zZMMBONDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMBANKL {
            get {
                return this.zZMMBANKLField;
            }
            set {
                this.zZMMBANKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMVLDSTART {
            get {
                return this.zZMMVLDSTARTField;
            }
            set {
                this.zZMMVLDSTARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMVLDEND {
            get {
                return this.zZMMVLDENDField;
            }
            set {
                this.zZMMVLDENDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMDLVTIME {
            get {
                return this.zZMMDLVTIMEField;
            }
            set {
                this.zZMMDLVTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMUOT {
            get {
                return this.zZMMUOTField;
            }
            set {
                this.zZMMUOTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPARTALLOW {
            get {
                return this.zZMMPARTALLOWField;
            }
            set {
                this.zZMMPARTALLOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAFE {
            get {
                return this.zZMMAFEField;
            }
            set {
                this.zZMMAFEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMTKDN {
            get {
                return this.zZMMTKDNField;
            }
            set {
                this.zZMMTKDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHNAME {
            get {
                return this.zZMMAUTHNAMEField;
            }
            set {
                this.zZMMAUTHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHPOS {
            get {
                return this.zZMMAUTHPOSField;
            }
            set {
                this.zZMMAUTHPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPYMMTD {
            get {
                return this.zZMMPYMMTDField;
            }
            set {
                this.zZMMPYMMTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIKO {
            get {
                return this.rESIKOField;
            }
            set {
                this.rESIKOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMKOMODITAS {
            get {
                return this.zZMMKOMODITASField;
            }
            set {
                this.zZMMKOMODITASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMSTATUSPT {
            get {
                return this.zZMMSTATUSPTField;
            }
            set {
                this.zZMMSTATUSPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPROCLIST {
            get {
                return this.zZMMPROCLISTField;
            }
            set {
                this.zZMMPROCLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMBIDLIST {
            get {
                return this.zZMMBIDLISTField;
            }
            set {
                this.zZMMBIDLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZIP2P_SUBBID {
            get {
                return this.zZIP2P_SUBBIDField;
            }
            set {
                this.zZIP2P_SUBBIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZIP2P_OWNEREST {
            get {
                return this.zZIP2P_OWNERESTField;
            }
            set {
                this.zZIP2P_OWNERESTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZIP2P_CURR {
            get {
                return this.zZIP2P_CURRField;
            }
            set {
                this.zZIP2P_CURRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSVERSIONS VERSIONS {
            get {
                return this.vERSIONSField;
            }
            set {
                this.vERSIONSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HEADERTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSHEADERTEXT[] HEADERTEXT {
            get {
                return this.hEADERTEXTField;
            }
            set {
                this.hEADERTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSPOADDRVENDOR POADDRVENDOR {
            get {
                return this.pOADDRVENDORField;
            }
            set {
                this.pOADDRVENDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POPARTNER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSPOPARTNER[] POPARTNER {
            get {
                return this.pOPARTNERField;
            }
            set {
                this.pOPARTNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIMITS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSLIMITS[] LIMITS {
            get {
                return this.lIMITSField;
            }
            set {
                this.lIMITSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SERVICE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSSERVICE[] SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSRVACCESSVALUES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSPOSRVACCESSVALUES[] POSRVACCESSVALUES {
            get {
                return this.pOSRVACCESSVALUESField;
            }
            set {
                this.pOSRVACCESSVALUESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSVERSIONS {
        
        private string cOMPLETEDField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPLETED {
            get {
                return this.cOMPLETEDField;
            }
            set {
                this.cOMPLETEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSHEADERTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSPOADDRVENDOR {
        
        private string nAMEField;
        
        private string nAME_2Field;
        
        private string sTREETField;
        
        private string hOUSE_NOField;
        
        private string pOSTL_COD1Field;
        
        private string cITYField;
        
        private string cOUNTRYField;
        
        private string tEL1_NUMBRField;
        
        private string fAX_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_2 {
            get {
                return this.nAME_2Field;
            }
            set {
                this.nAME_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NO {
            get {
                return this.hOUSE_NOField;
            }
            set {
                this.hOUSE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTL_COD1 {
            get {
                return this.pOSTL_COD1Field;
            }
            set {
                this.pOSTL_COD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL1_NUMBR {
            get {
                return this.tEL1_NUMBRField;
            }
            set {
                this.tEL1_NUMBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FAX_NUMBER {
            get {
                return this.fAX_NUMBERField;
            }
            set {
                this.fAX_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSPOPARTNER {
        
        private string pARTNERDESCField;
        
        private string bUSPARTNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARTNERDESC {
            get {
                return this.pARTNERDESCField;
            }
            set {
                this.pARTNERDESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSPARTNO {
            get {
                return this.bUSPARTNOField;
            }
            set {
                this.bUSPARTNOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMS {
        
        private string eBELPField;
        
        private string dELETE_INDField;
        
        private string pSTYPField;
        
        private string kNTTPField;
        
        private string mWSKZField;
        
        private string mATNRField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private string mATKLField;
        
        private string tXZ01Field;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string nETPRField;
        
        private string pEINHField;
        
        private string bPRMEField;
        
        private string wEUNBField;
        
        private string rEPOSField;
        
        private string wEBREField;
        
        private string wEPOSField;
        
        private string eLIKZField;
        
        private string eREKZField;
        
        private string aFNAMField;
        
        private string kONNRField;
        
        private string kTPNRField;
        
        private string pCKG_NOField;
        
        private string lEBREField;
        
        private string pREQ_NOField;
        
        private string pREQ_ITEMField;
        
        private string dISTRIBField;
        
        private dt_po_requestPO_DETAILSITEMSADDRDELIVERY[] aDDRDELIVERYField;
        
        private dt_po_requestPO_DETAILSITEMSITEMTEXT[] iTEMTEXTField;
        
        private dt_po_requestPO_DETAILSITEMSSCHEDULE[] sCHEDULEField;
        
        private dt_po_requestPO_DETAILSITEMSACCNTASSIGNMENT[] aCCNTASSIGNMENTField;
        
        private dt_po_requestPO_DETAILSITEMSCONDITIONTYPE[] cONDITIONTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTYP {
            get {
                return this.pSTYPField;
            }
            set {
                this.pSTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KNTTP {
            get {
                return this.kNTTPField;
            }
            set {
                this.kNTTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MWSKZ {
            get {
                return this.mWSKZField;
            }
            set {
                this.mWSKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATKL {
            get {
                return this.mATKLField;
            }
            set {
                this.mATKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXZ01 {
            get {
                return this.tXZ01Field;
            }
            set {
                this.tXZ01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETPR {
            get {
                return this.nETPRField;
            }
            set {
                this.nETPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEINH {
            get {
                return this.pEINHField;
            }
            set {
                this.pEINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPRME {
            get {
                return this.bPRMEField;
            }
            set {
                this.bPRMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEUNB {
            get {
                return this.wEUNBField;
            }
            set {
                this.wEUNBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REPOS {
            get {
                return this.rEPOSField;
            }
            set {
                this.rEPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEBRE {
            get {
                return this.wEBREField;
            }
            set {
                this.wEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEPOS {
            get {
                return this.wEPOSField;
            }
            set {
                this.wEPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ELIKZ {
            get {
                return this.eLIKZField;
            }
            set {
                this.eLIKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EREKZ {
            get {
                return this.eREKZField;
            }
            set {
                this.eREKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AFNAM {
            get {
                return this.aFNAMField;
            }
            set {
                this.aFNAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KONNR {
            get {
                return this.kONNRField;
            }
            set {
                this.kONNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KTPNR {
            get {
                return this.kTPNRField;
            }
            set {
                this.kTPNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEBRE {
            get {
                return this.lEBREField;
            }
            set {
                this.lEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NO {
            get {
                return this.pREQ_NOField;
            }
            set {
                this.pREQ_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_ITEM {
            get {
                return this.pREQ_ITEMField;
            }
            set {
                this.pREQ_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTRIB {
            get {
                return this.dISTRIBField;
            }
            set {
                this.dISTRIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRDELIVERY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMSADDRDELIVERY[] ADDRDELIVERY {
            get {
                return this.aDDRDELIVERYField;
            }
            set {
                this.aDDRDELIVERYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMSITEMTEXT[] ITEMTEXT {
            get {
                return this.iTEMTEXTField;
            }
            set {
                this.iTEMTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SCHEDULE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMSSCHEDULE[] SCHEDULE {
            get {
                return this.sCHEDULEField;
            }
            set {
                this.sCHEDULEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCNTASSIGNMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMSACCNTASSIGNMENT[] ACCNTASSIGNMENT {
            get {
                return this.aCCNTASSIGNMENTField;
            }
            set {
                this.aCCNTASSIGNMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONDITIONTYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_requestPO_DETAILSITEMSCONDITIONTYPE[] CONDITIONTYPE {
            get {
                return this.cONDITIONTYPEField;
            }
            set {
                this.cONDITIONTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMSADDRDELIVERY {
        
        private string aDDR_NOField;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string cITY1Field;
        
        private string pOST_CODE1Field;
        
        private string sTREETField;
        
        private string hOUSE_NUM1Field;
        
        private string lAND1Field;
        
        private string rEGIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDR_NO {
            get {
                return this.aDDR_NOField;
            }
            set {
                this.aDDR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME2 {
            get {
                return this.nAME2Field;
            }
            set {
                this.nAME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY1 {
            get {
                return this.cITY1Field;
            }
            set {
                this.cITY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POST_CODE1 {
            get {
                return this.pOST_CODE1Field;
            }
            set {
                this.pOST_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NUM1 {
            get {
                return this.hOUSE_NUM1Field;
            }
            set {
                this.hOUSE_NUM1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LAND1 {
            get {
                return this.lAND1Field;
            }
            set {
                this.lAND1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMSITEMTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMSSCHEDULE {
        
        private string eTENRField;
        
        private string eINDTField;
        
        private string qUANTITYField;
        
        private string bANFNField;
        
        private string bNFPOField;
        
        private string dELETE_INDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETENR {
            get {
                return this.eTENRField;
            }
            set {
                this.eTENRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANFN {
            get {
                return this.bANFNField;
            }
            set {
                this.bANFNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BNFPO {
            get {
                return this.bNFPOField;
            }
            set {
                this.bNFPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMSACCNTASSIGNMENT {
        
        private string zEKKNField;
        
        private string dELETE_INDField;
        
        private string mENGEField;
        
        private string vPROZField;
        
        private string sAKTOField;
        
        private string kOSTLField;
        
        private string aUFNRField;
        
        private string pS_PSP_PNRField;
        
        private string nPLNRField;
        
        private string fISTLField;
        
        private string fIPOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN {
            get {
                return this.zEKKNField;
            }
            set {
                this.zEKKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VPROZ {
            get {
                return this.vPROZField;
            }
            set {
                this.vPROZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAKTO {
            get {
                return this.sAKTOField;
            }
            set {
                this.sAKTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PS_PSP_PNR {
            get {
                return this.pS_PSP_PNRField;
            }
            set {
                this.pS_PSP_PNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NPLNR {
            get {
                return this.nPLNRField;
            }
            set {
                this.nPLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FISTL {
            get {
                return this.fISTLField;
            }
            set {
                this.fISTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIPOS {
            get {
                return this.fIPOSField;
            }
            set {
                this.fIPOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSITEMSCONDITIONTYPE {
        
        private string sTUNRField;
        
        private string dZAEHKField;
        
        private string kSCHLField;
        
        private string kBETRField;
        
        private string wAERSField;
        
        private string lIFNRField;
        
        private string cHANGE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STUNR {
            get {
                return this.sTUNRField;
            }
            set {
                this.sTUNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DZAEHK {
            get {
                return this.dZAEHKField;
            }
            set {
                this.dZAEHKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KSCHL {
            get {
                return this.kSCHLField;
            }
            set {
                this.kSCHLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KBETR {
            get {
                return this.kBETRField;
            }
            set {
                this.kBETRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHANGE_ID {
            get {
                return this.cHANGE_IDField;
            }
            set {
                this.cHANGE_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSLIMITS {
        
        private string pACKNOField;
        
        private string sUMLIMITField;
        
        private string sUMNOLIMField;
        
        private string cOMMITMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUMLIMIT {
            get {
                return this.sUMLIMITField;
            }
            set {
                this.sUMLIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUMNOLIM {
            get {
                return this.sUMNOLIMField;
            }
            set {
                this.sUMNOLIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMITMENT {
            get {
                return this.cOMMITMENTField;
            }
            set {
                this.cOMMITMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSSERVICE {
        
        private string pACKNO_EXTField;
        
        private string iNTROW_EXTField;
        
        private string eXTROWField;
        
        private string oUTL_INDField;
        
        private string sUB_PACKNOField;
        
        private string sRVPOSField;
        
        private string dEL_INDField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string pEINHField;
        
        private string bRTWRField;
        
        private string tXZ01Field;
        
        private string pLN_PACKNOField;
        
        private string pLN_INTROWField;
        
        private string dISTRIBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO_EXT {
            get {
                return this.pACKNO_EXTField;
            }
            set {
                this.pACKNO_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW_EXT {
            get {
                return this.iNTROW_EXTField;
            }
            set {
                this.iNTROW_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTROW {
            get {
                return this.eXTROWField;
            }
            set {
                this.eXTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OUTL_IND {
            get {
                return this.oUTL_INDField;
            }
            set {
                this.oUTL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUB_PACKNO {
            get {
                return this.sUB_PACKNOField;
            }
            set {
                this.sUB_PACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SRVPOS {
            get {
                return this.sRVPOSField;
            }
            set {
                this.sRVPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_IND {
            get {
                return this.dEL_INDField;
            }
            set {
                this.dEL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEINH {
            get {
                return this.pEINHField;
            }
            set {
                this.pEINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTWR {
            get {
                return this.bRTWRField;
            }
            set {
                this.bRTWRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXZ01 {
            get {
                return this.tXZ01Field;
            }
            set {
                this.tXZ01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLN_PACKNO {
            get {
                return this.pLN_PACKNOField;
            }
            set {
                this.pLN_PACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLN_INTROW {
            get {
                return this.pLN_INTROWField;
            }
            set {
                this.pLN_INTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTRIB {
            get {
                return this.dISTRIBField;
            }
            set {
                this.dISTRIBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_requestPO_DETAILSPOSRVACCESSVALUES {
        
        private string pACKNOField;
        
        private string iNTROWField;
        
        private string nUMKNField;
        
        private string zEKKNField;
        
        private string mENGEField;
        
        private string wPROZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW {
            get {
                return this.iNTROWField;
            }
            set {
                this.iNTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMKN {
            get {
                return this.nUMKNField;
            }
            set {
                this.nUMKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN {
            get {
                return this.zEKKNField;
            }
            set {
                this.zEKKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WPROZ {
            get {
                return this.wPROZField;
            }
            set {
                this.wPROZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_responsePO_DETAILS {
        
        private string mANDTField;
        
        private string eBELN_EXTField;
        
        private string eBELNField;
        
        private string fRGKEField;
        
        private string cOMM_FLAGField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private dt_po_responsePO_DETAILSMSG_DETAILS[] mSG_DETAILSField;
        
        private dt_po_responsePO_DETAILSITEMS[] iTEMSField;
        
        private dt_po_responsePO_DETAILSSERVICE[] sERVICEField;
        
        private dt_po_responsePO_DETAILSPOSRVACCESSVALUES[] pOSRVACCESSVALUESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN_EXT {
            get {
                return this.eBELN_EXTField;
            }
            set {
                this.eBELN_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FRGKE {
            get {
                return this.fRGKEField;
            }
            set {
                this.fRGKEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMM_FLAG {
            get {
                return this.cOMM_FLAGField;
            }
            set {
                this.cOMM_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSG_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_responsePO_DETAILSMSG_DETAILS[] MSG_DETAILS {
            get {
                return this.mSG_DETAILSField;
            }
            set {
                this.mSG_DETAILSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_responsePO_DETAILSITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SERVICE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_responsePO_DETAILSSERVICE[] SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSRVACCESSVALUES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_po_responsePO_DETAILSPOSRVACCESSVALUES[] POSRVACCESSVALUES {
            get {
                return this.pOSRVACCESSVALUESField;
            }
            set {
                this.pOSRVACCESSVALUESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_responsePO_DETAILSMSG_DETAILS {
        
        private string tYPEField;
        
        private string mSG_DETField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSG_DET {
            get {
                return this.mSG_DETField;
            }
            set {
                this.mSG_DETField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_responsePO_DETAILSITEMS {
        
        private string eBELP_EXTField;
        
        private string eBELPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP_EXT {
            get {
                return this.eBELP_EXTField;
            }
            set {
                this.eBELP_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_responsePO_DETAILSSERVICE {
        
        private string pACKNO_EXTField;
        
        private string iNTROW_EXTField;
        
        private string pACKNOField;
        
        private string iNTROWField;
        
        private string eXTROWField;
        
        private string sUB_PACKNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO_EXT {
            get {
                return this.pACKNO_EXTField;
            }
            set {
                this.pACKNO_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW_EXT {
            get {
                return this.iNTROW_EXTField;
            }
            set {
                this.iNTROW_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW {
            get {
                return this.iNTROWField;
            }
            set {
                this.iNTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTROW {
            get {
                return this.eXTROWField;
            }
            set {
                this.eXTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUB_PACKNO {
            get {
                return this.sUB_PACKNOField;
            }
            set {
                this.sUB_PACKNOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_po_responsePO_DETAILSPOSRVACCESSVALUES {
        
        private string pACKNO_EXTField;
        
        private string iNTROW_EXTField;
        
        private string nUMKN_EXTField;
        
        private string pACKNOField;
        
        private string iNTROWField;
        
        private string nUMKNField;
        
        private string zEKKN_EXTField;
        
        private string zEKKNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO_EXT {
            get {
                return this.pACKNO_EXTField;
            }
            set {
                this.pACKNO_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW_EXT {
            get {
                return this.iNTROW_EXTField;
            }
            set {
                this.iNTROW_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMKN_EXT {
            get {
                return this.nUMKN_EXTField;
            }
            set {
                this.nUMKN_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW {
            get {
                return this.iNTROWField;
            }
            set {
                this.iNTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMKN {
            get {
                return this.nUMKNField;
            }
            set {
                this.nUMKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN_EXT {
            get {
                return this.zEKKN_EXTField;
            }
            set {
                this.zEKKN_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN {
            get {
                return this.zEKKNField;
            }
            set {
                this.zEKKNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mi_os_poCompletedEventHandler(object sender, mi_os_poCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mi_os_poCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mi_os_poCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_po_responsePO_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_po_responsePO_DETAILS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591