//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIHost2host.PO_InqServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mi_os_GetPOBinding", Namespace="urn:pertamina:po")]
    public partial class mi_os_GetPOService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mi_os_GetPOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mi_os_GetPOService() {
            this.Url = global::APIHost2host.Properties.Settings.Default.APIHost2host_PO_InqService_mi_os_GetPOService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mi_os_GetPOCompletedEventHandler mi_os_GetPOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("mt_GetPO_Response", Namespace="urn:pertamina:po")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("PO_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_GetPO_ResponsePO_DETAILS[] mi_os_GetPO([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:pertamina:po")] [System.Xml.Serialization.XmlArrayItemAttribute("PO_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] dt_GetPO_RequestPO_DETAILS[] mt_GetPO_Request) {
            object[] results = this.Invoke("mi_os_GetPO", new object[] {
                        mt_GetPO_Request});
            return ((dt_GetPO_ResponsePO_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void mi_os_GetPOAsync(dt_GetPO_RequestPO_DETAILS[] mt_GetPO_Request) {
            this.mi_os_GetPOAsync(mt_GetPO_Request, null);
        }
        
        /// <remarks/>
        public void mi_os_GetPOAsync(dt_GetPO_RequestPO_DETAILS[] mt_GetPO_Request, object userState) {
            if ((this.mi_os_GetPOOperationCompleted == null)) {
                this.mi_os_GetPOOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmi_os_GetPOOperationCompleted);
            }
            this.InvokeAsync("mi_os_GetPO", new object[] {
                        mt_GetPO_Request}, this.mi_os_GetPOOperationCompleted, userState);
        }
        
        private void Onmi_os_GetPOOperationCompleted(object arg) {
            if ((this.mi_os_GetPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mi_os_GetPOCompleted(this, new mi_os_GetPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_RequestPO_DETAILS {
        
        private string cLIENTField;
        
        private string pO_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLIENT {
            get {
                return this.cLIENTField;
            }
            set {
                this.cLIENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PO_NUMBER {
            get {
                return this.pO_NUMBERField;
            }
            set {
                this.pO_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILS {
        
        private string pO_NUMBERField;
        
        private string dOC_TYPEField;
        
        private string dOC_DATEField;
        
        private string vENDORField;
        
        private string cURRENCYField;
        
        private string pUR_GROUPField;
        
        private string pURCH_ORGField;
        
        private string pMNTTRMSField;
        
        private string iNCOTERMS1Field;
        
        private string iNCOTERMS2Field;
        
        private string eXCH_RATEField;
        
        private string rEL_INDField;
        
        private string rEL_STATUSField;
        
        private string zZMMMULTIPLIERField;
        
        private string zZMMAFEField;
        
        private string zZMMTKDNField;
        
        private string zZMMAUTHNAMEField;
        
        private string zZMMAUTHPOSField;
        
        private string zZMMPYMMTDField;
        
        private string zZMMSPMKField;
        
        private string zZMMNILBIAYAField;
        
        private string zZMMPENAWALField;
        
        private string zZIP2P_OWNERESTField;
        
        private string zZHSERISKField;
        
        private string zZMMBIDLISTField;
        
        private string zZSUBIDField;
        
        private string zZMMKOMODITASField;
        
        private string zZMMPROCLISTField;
        
        private string zZMMPROCLISTIField;
        
        private dt_GetPO_ResponsePO_DETAILSPOTEXTHEADER[] pOTEXTHEADERField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEM[] pOITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PO_NUMBER {
            get {
                return this.pO_NUMBERField;
            }
            set {
                this.pO_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDOR {
            get {
                return this.vENDORField;
            }
            set {
                this.vENDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUR_GROUP {
            get {
                return this.pUR_GROUPField;
            }
            set {
                this.pUR_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PURCH_ORG {
            get {
                return this.pURCH_ORGField;
            }
            set {
                this.pURCH_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PMNTTRMS {
            get {
                return this.pMNTTRMSField;
            }
            set {
                this.pMNTTRMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOTERMS1 {
            get {
                return this.iNCOTERMS1Field;
            }
            set {
                this.iNCOTERMS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOTERMS2 {
            get {
                return this.iNCOTERMS2Field;
            }
            set {
                this.iNCOTERMS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXCH_RATE {
            get {
                return this.eXCH_RATEField;
            }
            set {
                this.eXCH_RATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REL_IND {
            get {
                return this.rEL_INDField;
            }
            set {
                this.rEL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REL_STATUS {
            get {
                return this.rEL_STATUSField;
            }
            set {
                this.rEL_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMMULTIPLIER {
            get {
                return this.zZMMMULTIPLIERField;
            }
            set {
                this.zZMMMULTIPLIERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAFE {
            get {
                return this.zZMMAFEField;
            }
            set {
                this.zZMMAFEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMTKDN {
            get {
                return this.zZMMTKDNField;
            }
            set {
                this.zZMMTKDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHNAME {
            get {
                return this.zZMMAUTHNAMEField;
            }
            set {
                this.zZMMAUTHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHPOS {
            get {
                return this.zZMMAUTHPOSField;
            }
            set {
                this.zZMMAUTHPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPYMMTD {
            get {
                return this.zZMMPYMMTDField;
            }
            set {
                this.zZMMPYMMTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMSPMK {
            get {
                return this.zZMMSPMKField;
            }
            set {
                this.zZMMSPMKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMNILBIAYA {
            get {
                return this.zZMMNILBIAYAField;
            }
            set {
                this.zZMMNILBIAYAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPENAWAL {
            get {
                return this.zZMMPENAWALField;
            }
            set {
                this.zZMMPENAWALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZIP2P_OWNEREST {
            get {
                return this.zZIP2P_OWNERESTField;
            }
            set {
                this.zZIP2P_OWNERESTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZHSERISK {
            get {
                return this.zZHSERISKField;
            }
            set {
                this.zZHSERISKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMBIDLIST {
            get {
                return this.zZMMBIDLISTField;
            }
            set {
                this.zZMMBIDLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZSUBID {
            get {
                return this.zZSUBIDField;
            }
            set {
                this.zZSUBIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMKOMODITAS {
            get {
                return this.zZMMKOMODITASField;
            }
            set {
                this.zZMMKOMODITASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPROCLIST {
            get {
                return this.zZMMPROCLISTField;
            }
            set {
                this.zZMMPROCLISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMPROCLISTI {
            get {
                return this.zZMMPROCLISTIField;
            }
            set {
                this.zZMMPROCLISTIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POTEXTHEADER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOTEXTHEADER[] POTEXTHEADER {
            get {
                return this.pOTEXTHEADERField;
            }
            set {
                this.pOTEXTHEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEM[] POITEM {
            get {
                return this.pOITEMField;
            }
            set {
                this.pOITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOTEXTHEADER {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEM {
        
        private string pO_ITEMField;
        
        private string mATERIALField;
        
        private string sHORT_TEXTField;
        
        private string qUANTITYField;
        
        private string uNITField;
        
        private string nET_PRICEField;
        
        private string pRICE_UNITField;
        
        private string pLANTField;
        
        private string pREQ_NOField;
        
        private string pREQ_ITEMField;
        
        private string rFQField;
        
        private string rFQ_ITEMField;
        
        private string pREQ_NAMEField;
        
        private string iTEM_CATField;
        
        private string aCCTASSCATField;
        
        private string mAT_GRPField;
        
        private string sTORE_LOCField;
        
        private string bATCHField;
        
        private string aGREEMENTField;
        
        private string aGMT_ITEMField;
        
        private string oVERDELTOLField;
        
        private string uNDER_TOLField;
        
        private string uNLIMITEDField;
        
        private string gR_INDField;
        
        private string gR_NON_VALField;
        
        private string nO_MORE_GRField;
        
        private string iR_INDField;
        
        private string fINAL_INVField;
        
        private string gR_BASEDIVField;
        
        private string pART_INVField;
        
        private string tAX_CODEField;
        
        private string pCKG_NOField;
        
        private string dISTRIBField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOTEXTITEM[] pOTEXTITEMField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOACCOUNT[] pOACCOUNTField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOSCHEDULE[] pOSCHEDULEField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOADDRDELIVERY[] pOADDRDELIVERYField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOLIMITS[] pOLIMITSField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICES[] pOSERVICESField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOSRVACCESSVALUES[] pOSRVACCESSVALUESField;
        
        private dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICETEXT[] pOSERVICETEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PO_ITEM {
            get {
                return this.pO_ITEMField;
            }
            set {
                this.pO_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NET_PRICE {
            get {
                return this.nET_PRICEField;
            }
            set {
                this.nET_PRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE_UNIT {
            get {
                return this.pRICE_UNITField;
            }
            set {
                this.pRICE_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NO {
            get {
                return this.pREQ_NOField;
            }
            set {
                this.pREQ_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_ITEM {
            get {
                return this.pREQ_ITEMField;
            }
            set {
                this.pREQ_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RFQ {
            get {
                return this.rFQField;
            }
            set {
                this.rFQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RFQ_ITEM {
            get {
                return this.rFQ_ITEMField;
            }
            set {
                this.rFQ_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NAME {
            get {
                return this.pREQ_NAMEField;
            }
            set {
                this.pREQ_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_CAT {
            get {
                return this.iTEM_CATField;
            }
            set {
                this.iTEM_CATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCTASSCAT {
            get {
                return this.aCCTASSCATField;
            }
            set {
                this.aCCTASSCATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAT_GRP {
            get {
                return this.mAT_GRPField;
            }
            set {
                this.mAT_GRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STORE_LOC {
            get {
                return this.sTORE_LOCField;
            }
            set {
                this.sTORE_LOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BATCH {
            get {
                return this.bATCHField;
            }
            set {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGREEMENT {
            get {
                return this.aGREEMENTField;
            }
            set {
                this.aGREEMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGMT_ITEM {
            get {
                return this.aGMT_ITEMField;
            }
            set {
                this.aGMT_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OVERDELTOL {
            get {
                return this.oVERDELTOLField;
            }
            set {
                this.oVERDELTOLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNDER_TOL {
            get {
                return this.uNDER_TOLField;
            }
            set {
                this.uNDER_TOLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNLIMITED {
            get {
                return this.uNLIMITEDField;
            }
            set {
                this.uNLIMITEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GR_IND {
            get {
                return this.gR_INDField;
            }
            set {
                this.gR_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GR_NON_VAL {
            get {
                return this.gR_NON_VALField;
            }
            set {
                this.gR_NON_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NO_MORE_GR {
            get {
                return this.nO_MORE_GRField;
            }
            set {
                this.nO_MORE_GRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IR_IND {
            get {
                return this.iR_INDField;
            }
            set {
                this.iR_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FINAL_INV {
            get {
                return this.fINAL_INVField;
            }
            set {
                this.fINAL_INVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GR_BASEDIV {
            get {
                return this.gR_BASEDIVField;
            }
            set {
                this.gR_BASEDIVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PART_INV {
            get {
                return this.pART_INVField;
            }
            set {
                this.pART_INVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAX_CODE {
            get {
                return this.tAX_CODEField;
            }
            set {
                this.tAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTRIB {
            get {
                return this.dISTRIBField;
            }
            set {
                this.dISTRIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POTEXTITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOTEXTITEM[] POTEXTITEM {
            get {
                return this.pOTEXTITEMField;
            }
            set {
                this.pOTEXTITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOACCOUNT[] POACCOUNT {
            get {
                return this.pOACCOUNTField;
            }
            set {
                this.pOACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSCHEDULE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOSCHEDULE[] POSCHEDULE {
            get {
                return this.pOSCHEDULEField;
            }
            set {
                this.pOSCHEDULEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POADDRDELIVERY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOADDRDELIVERY[] POADDRDELIVERY {
            get {
                return this.pOADDRDELIVERYField;
            }
            set {
                this.pOADDRDELIVERYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POLIMITS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOLIMITS[] POLIMITS {
            get {
                return this.pOLIMITSField;
            }
            set {
                this.pOLIMITSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSERVICES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICES[] POSERVICES {
            get {
                return this.pOSERVICESField;
            }
            set {
                this.pOSERVICESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSRVACCESSVALUES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOSRVACCESSVALUES[] POSRVACCESSVALUES {
            get {
                return this.pOSRVACCESSVALUESField;
            }
            set {
                this.pOSRVACCESSVALUESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSERVICETEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICETEXT[] POSERVICETEXT {
            get {
                return this.pOSERVICETEXTField;
            }
            set {
                this.pOSERVICETEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOTEXTITEM {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOACCOUNT {
        
        private string sERIAL_NOField;
        
        private string g_L_ACCTField;
        
        private string cOST_CTRField;
        
        private string oRDER_NOField;
        
        private string wBS_ELEM_EField;
        
        private string nETWORKField;
        
        private string aCTIVITYField;
        
        private string cMMT_ITEM_LONGField;
        
        private string aSSET_NOField;
        
        private string qUANTITYField;
        
        private string dISTR_PERCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string G_L_ACCT {
            get {
                return this.g_L_ACCTField;
            }
            set {
                this.g_L_ACCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COST_CTR {
            get {
                return this.cOST_CTRField;
            }
            set {
                this.cOST_CTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDER_NO {
            get {
                return this.oRDER_NOField;
            }
            set {
                this.oRDER_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WBS_ELEM_E {
            get {
                return this.wBS_ELEM_EField;
            }
            set {
                this.wBS_ELEM_EField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETWORK {
            get {
                return this.nETWORKField;
            }
            set {
                this.nETWORKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACTIVITY {
            get {
                return this.aCTIVITYField;
            }
            set {
                this.aCTIVITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CMMT_ITEM_LONG {
            get {
                return this.cMMT_ITEM_LONGField;
            }
            set {
                this.cMMT_ITEM_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSET_NO {
            get {
                return this.aSSET_NOField;
            }
            set {
                this.aSSET_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTR_PERC {
            get {
                return this.dISTR_PERCField;
            }
            set {
                this.dISTR_PERCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOSCHEDULE {
        
        private string dELIV_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELIV_DATE {
            get {
                return this.dELIV_DATEField;
            }
            set {
                this.dELIV_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOADDRDELIVERY {
        
        private string nAMEField;
        
        private string nAME_2Field;
        
        private string sTREETField;
        
        private string hOUSE_NOField;
        
        private string cITYField;
        
        private string pOSTL_COD1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_2 {
            get {
                return this.nAME_2Field;
            }
            set {
                this.nAME_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NO {
            get {
                return this.hOUSE_NOField;
            }
            set {
                this.hOUSE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTL_COD1 {
            get {
                return this.pOSTL_COD1Field;
            }
            set {
                this.pOSTL_COD1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOLIMITS {
        
        private string pCKG_NOField;
        
        private string lIMITField;
        
        private string eXP_VALUEField;
        
        private string nO_LIMITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIMIT {
            get {
                return this.lIMITField;
            }
            set {
                this.lIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXP_VALUE {
            get {
                return this.eXP_VALUEField;
            }
            set {
                this.eXP_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NO_LIMIT {
            get {
                return this.nO_LIMITField;
            }
            set {
                this.nO_LIMITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICES {
        
        private string pCKG_NOField;
        
        private string lINE_NOField;
        
        private string eXT_LINEField;
        
        private string sERVICEField;
        
        private string sHORT_TEXTField;
        
        private string qUANTITYField;
        
        private string bASE_UOMField;
        
        private string gROSS_VALField;
        
        private string pRICE_UNITField;
        
        private string nET_VALUEField;
        
        private string dISTRIBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINE_NO {
            get {
                return this.lINE_NOField;
            }
            set {
                this.lINE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXT_LINE {
            get {
                return this.eXT_LINEField;
            }
            set {
                this.eXT_LINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROSS_VAL {
            get {
                return this.gROSS_VALField;
            }
            set {
                this.gROSS_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE_UNIT {
            get {
                return this.pRICE_UNITField;
            }
            set {
                this.pRICE_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NET_VALUE {
            get {
                return this.nET_VALUEField;
            }
            set {
                this.nET_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTRIB {
            get {
                return this.dISTRIBField;
            }
            set {
                this.dISTRIBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOSRVACCESSVALUES {
        
        private string pCKG_NOField;
        
        private string lINE_NOField;
        
        private string sERNO_LINEField;
        
        private string pERCENTAGEField;
        
        private string sERIAL_NOField;
        
        private string qUANTITYField;
        
        private string nET_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINE_NO {
            get {
                return this.lINE_NOField;
            }
            set {
                this.lINE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERNO_LINE {
            get {
                return this.sERNO_LINEField;
            }
            set {
                this.sERNO_LINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERCENTAGE {
            get {
                return this.pERCENTAGEField;
            }
            set {
                this.pERCENTAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NET_VALUE {
            get {
                return this.nET_VALUEField;
            }
            set {
                this.nET_VALUEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:po")]
    public partial class dt_GetPO_ResponsePO_DETAILSPOITEMPOSERVICETEXT {
        
        private string pCKG_NOField;
        
        private string lINE_NOField;
        
        private string tEXT_IDField;
        
        private string fORMAT_COLField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINE_NO {
            get {
                return this.lINE_NOField;
            }
            set {
                this.lINE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FORMAT_COL {
            get {
                return this.fORMAT_COLField;
            }
            set {
                this.fORMAT_COLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mi_os_GetPOCompletedEventHandler(object sender, mi_os_GetPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mi_os_GetPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mi_os_GetPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_GetPO_ResponsePO_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_GetPO_ResponsePO_DETAILS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591