//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIHost2host.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev02xi.pertamina.com:8000/sap/xi/engine?type=entry&version=3.0&Sender.Ser" +
            "vice=PIPS_D&Interface=urn%3Apertamina%3Agr%5Emi_os_gr_pips")]
        public string APIHost2host_GR_Services_mi_os_gr_pipsService {
            get {
                return ((string)(this["APIHost2host_GR_Services_mi_os_gr_pipsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev02xi.pertamina.com:8000/sap/xi/engine?type=entry&version=3.0&Sender.Ser" +
            "vice=PIPS_D&Interface=urn%3Apertamina%3Apo%5Emi_os_po")]
        public string APIHost2host_PO_Services2_mi_os_poService {
            get {
                return ((string)(this["APIHost2host_PO_Services2_mi_os_poService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piwddmz1.pertamina.com:8163/sap/xi/engine?type=entry&version=3.0&Sender.Se" +
            "rvice=PIPS_P&Interface=urn%3Apertamina%3Apo%5Emi_os_GetPO")]
        public string APIHost2host_PO_InqService_mi_os_GetPOService {
            get {
                return ((string)(this["APIHost2host_PO_InqService_mi_os_GetPOService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piwddmz1.pertamina.com:8163/sap/xi/engine?type=entry&version=3.0&Sender.Se" +
            "rvice=PIPS_P&Interface=urn%3Apertamina%3Apr%5Emi_os_GetPR")]
        public string APIHost2host_PR_InqServices_mi_os_GetPRService {
            get {
                return ((string)(this["APIHost2host_PR_InqServices_mi_os_GetPRService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piwddmz1.pertamina.com:8163/sap/xi/engine?type=entry&version=3.0&Sender.Se" +
            "rvice=PIPS_P&Interface=urn%3Apertamina%3Arfq%5Emi_os_rfqpo")]
        public string SCMONLINE_Web_mi_os_rfqpo_web_mi_os_rfqpoService {
            get {
                return ((string)(this["SCMONLINE_Web_mi_os_rfqpo_web_mi_os_rfqpoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev02xi.pertamina.com:8000/sap/xi/engine?type=entry&version=3.0&Sender.Ser" +
            "vice=PIPS_D&Interface=urn%3Apertamina%3Arfq%5Emi_os_rfqpo")]
        public string APIHost2host_RFQ_Services_mi_os_rfqpoService {
            get {
                return ((string)(this["APIHost2host_RFQ_Services_mi_os_rfqpoService"]));
            }
        }
    }
}
