//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIHost2host.RFQ_Services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mi_os_rfqpoBinding", Namespace="urn:pertamina:rfq")]
    public partial class mi_os_rfqpoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mi_os_rfqpoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mi_os_rfqpoService() {
            this.Url = global::APIHost2host.Properties.Settings.Default.APIHost2host_RFQ_Services_mi_os_rfqpoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mi_os_rfqpoCompletedEventHandler mi_os_rfqpoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("mt_rfqpo_response", Namespace="urn:pertamina:rfq")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("RFQPO_DETAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_rfqpo_responseRFQPO_DETAIL[] mi_os_rfqpo([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:pertamina:rfq")] dt_rfqpo_request mt_rfqpo_request) {
            object[] results = this.Invoke("mi_os_rfqpo", new object[] {
                        mt_rfqpo_request});
            return ((dt_rfqpo_responseRFQPO_DETAIL[])(results[0]));
        }
        
        /// <remarks/>
        public void mi_os_rfqpoAsync(dt_rfqpo_request mt_rfqpo_request) {
            this.mi_os_rfqpoAsync(mt_rfqpo_request, null);
        }
        
        /// <remarks/>
        public void mi_os_rfqpoAsync(dt_rfqpo_request mt_rfqpo_request, object userState) {
            if ((this.mi_os_rfqpoOperationCompleted == null)) {
                this.mi_os_rfqpoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmi_os_rfqpoOperationCompleted);
            }
            this.InvokeAsync("mi_os_rfqpo", new object[] {
                        mt_rfqpo_request}, this.mi_os_rfqpoOperationCompleted, userState);
        }
        
        private void Onmi_os_rfqpoOperationCompleted(object arg) {
            if ((this.mi_os_rfqpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mi_os_rfqpoCompleted(this, new mi_os_rfqpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_request {
        
        private dt_rfqpo_requestRFQPO_DETAIL rFQPO_DETAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_requestRFQPO_DETAIL RFQPO_DETAIL {
            get {
                return this.rFQPO_DETAILField;
            }
            set {
                this.rFQPO_DETAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_requestRFQPO_DETAIL {
        
        private string mANDTField;
        
        private string bUKRSField;
        
        private string eKORGField;
        
        private dt_rfqpo_requestRFQPO_DETAILBSART[] bSARTField;
        
        private dt_rfqpo_requestRFQPO_DETAILEKGRP[] eKGRPField;
        
        private dt_rfqpo_requestRFQPO_DETAILAEDAT[] aEDATField;
        
        private dt_rfqpo_requestRFQPO_DETAILEBELN[] eBELNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKORG {
            get {
                return this.eKORGField;
            }
            set {
                this.eKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BSART", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_requestRFQPO_DETAILBSART[] BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EKGRP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_requestRFQPO_DETAILEKGRP[] EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AEDAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_requestRFQPO_DETAILAEDAT[] AEDAT {
            get {
                return this.aEDATField;
            }
            set {
                this.aEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EBELN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_requestRFQPO_DETAILEBELN[] EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_requestRFQPO_DETAILBSART {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_requestRFQPO_DETAILEKGRP {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_requestRFQPO_DETAILAEDAT {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_requestRFQPO_DETAILEBELN {
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAIL {
        
        private string eBELNField;
        
        private string bSARTField;
        
        private string dELETE_INDField;
        
        private string aEDATField;
        
        private string bEDATField;
        
        private string lIFNRField;
        
        private string bUKRSField;
        
        private string wAERSField;
        
        private string eKORGField;
        
        private string wKURSField;
        
        private string eKGRPField;
        
        private string zTERMField;
        
        private string iNCO1Field;
        
        private string iNCO2Field;
        
        private string zZMMAUTHNAMEField;
        
        private string zZMMAUTHPOSField;
        
        private dt_rfqpo_responseRFQPO_DETAILHEADERTEXT[] hEADERTEXTField;
        
        private dt_rfqpo_responseRFQPO_DETAILPOADDRVENDOR pOADDRVENDORField;
        
        private dt_rfqpo_responseRFQPO_DETAILITEMS[] iTEMSField;
        
        private dt_rfqpo_responseRFQPO_DETAILLIMITS[] lIMITSField;
        
        private dt_rfqpo_responseRFQPO_DETAILSERVICE[] sERVICEField;
        
        private dt_rfqpo_responseRFQPO_DETAILPOSRVACCRESSVALUES[] pOSRVACCRESSVALUESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AEDAT {
            get {
                return this.aEDATField;
            }
            set {
                this.aEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEDAT {
            get {
                return this.bEDATField;
            }
            set {
                this.bEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKORG {
            get {
                return this.eKORGField;
            }
            set {
                this.eKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WKURS {
            get {
                return this.wKURSField;
            }
            set {
                this.wKURSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCO1 {
            get {
                return this.iNCO1Field;
            }
            set {
                this.iNCO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCO2 {
            get {
                return this.iNCO2Field;
            }
            set {
                this.iNCO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHNAME {
            get {
                return this.zZMMAUTHNAMEField;
            }
            set {
                this.zZMMAUTHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHPOS {
            get {
                return this.zZMMAUTHPOSField;
            }
            set {
                this.zZMMAUTHPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HEADERTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILHEADERTEXT[] HEADERTEXT {
            get {
                return this.hEADERTEXTField;
            }
            set {
                this.hEADERTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILPOADDRVENDOR POADDRVENDOR {
            get {
                return this.pOADDRVENDORField;
            }
            set {
                this.pOADDRVENDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LIMITS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILLIMITS[] LIMITS {
            get {
                return this.lIMITSField;
            }
            set {
                this.lIMITSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SERVICE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILSERVICE[] SERVICE {
            get {
                return this.sERVICEField;
            }
            set {
                this.sERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POSRVACCRESSVALUES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILPOSRVACCRESSVALUES[] POSRVACCRESSVALUES {
            get {
                return this.pOSRVACCRESSVALUESField;
            }
            set {
                this.pOSRVACCRESSVALUESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILHEADERTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILPOADDRVENDOR {
        
        private string nAMEField;
        
        private string nAME_2Field;
        
        private string sTREETField;
        
        private string hOUSE_NOField;
        
        private string pOSTL_COD1Field;
        
        private string cITYField;
        
        private string cOUNTRYField;
        
        private string tEL1_NUMBRField;
        
        private string fAX_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME_2 {
            get {
                return this.nAME_2Field;
            }
            set {
                this.nAME_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NO {
            get {
                return this.hOUSE_NOField;
            }
            set {
                this.hOUSE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTL_COD1 {
            get {
                return this.pOSTL_COD1Field;
            }
            set {
                this.pOSTL_COD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL1_NUMBR {
            get {
                return this.tEL1_NUMBRField;
            }
            set {
                this.tEL1_NUMBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FAX_NUMBER {
            get {
                return this.fAX_NUMBERField;
            }
            set {
                this.fAX_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILITEMS {
        
        private string eBELPField;
        
        private string dELETE_INDField;
        
        private string pSTYPField;
        
        private string kNTTPField;
        
        private string mWSKZField;
        
        private string mATNRField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private string mATKLField;
        
        private string tXZ01Field;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string nETPRField;
        
        private string pEINHField;
        
        private string bPRMEField;
        
        private string wEUNBField;
        
        private string rEPOSField;
        
        private string wEBREField;
        
        private string wEPOSField;
        
        private string eLIKZField;
        
        private string eREKZField;
        
        private string aFNAMField;
        
        private string kONNRField;
        
        private string kTPNRField;
        
        private string pCKG_NOField;
        
        private string lEBREField;
        
        private dt_rfqpo_responseRFQPO_DETAILITEMSITEMTEXT[] iTEMTEXTField;
        
        private dt_rfqpo_responseRFQPO_DETAILITEMSSCHEDULE[] sCHEDULEField;
        
        private dt_rfqpo_responseRFQPO_DETAILITEMSACCNTASSIGMENT[] aCCNTASSIGMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTYP {
            get {
                return this.pSTYPField;
            }
            set {
                this.pSTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KNTTP {
            get {
                return this.kNTTPField;
            }
            set {
                this.kNTTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MWSKZ {
            get {
                return this.mWSKZField;
            }
            set {
                this.mWSKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATKL {
            get {
                return this.mATKLField;
            }
            set {
                this.mATKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXZ01 {
            get {
                return this.tXZ01Field;
            }
            set {
                this.tXZ01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETPR {
            get {
                return this.nETPRField;
            }
            set {
                this.nETPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEINH {
            get {
                return this.pEINHField;
            }
            set {
                this.pEINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPRME {
            get {
                return this.bPRMEField;
            }
            set {
                this.bPRMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEUNB {
            get {
                return this.wEUNBField;
            }
            set {
                this.wEUNBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REPOS {
            get {
                return this.rEPOSField;
            }
            set {
                this.rEPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEBRE {
            get {
                return this.wEBREField;
            }
            set {
                this.wEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEPOS {
            get {
                return this.wEPOSField;
            }
            set {
                this.wEPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ELIKZ {
            get {
                return this.eLIKZField;
            }
            set {
                this.eLIKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EREKZ {
            get {
                return this.eREKZField;
            }
            set {
                this.eREKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AFNAM {
            get {
                return this.aFNAMField;
            }
            set {
                this.aFNAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KONNR {
            get {
                return this.kONNRField;
            }
            set {
                this.kONNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KTPNR {
            get {
                return this.kTPNRField;
            }
            set {
                this.kTPNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PCKG_NO {
            get {
                return this.pCKG_NOField;
            }
            set {
                this.pCKG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEBRE {
            get {
                return this.lEBREField;
            }
            set {
                this.lEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILITEMSITEMTEXT[] ITEMTEXT {
            get {
                return this.iTEMTEXTField;
            }
            set {
                this.iTEMTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SCHEDULE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILITEMSSCHEDULE[] SCHEDULE {
            get {
                return this.sCHEDULEField;
            }
            set {
                this.sCHEDULEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCNTASSIGMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_rfqpo_responseRFQPO_DETAILITEMSACCNTASSIGMENT[] ACCNTASSIGMENT {
            get {
                return this.aCCNTASSIGMENTField;
            }
            set {
                this.aCCNTASSIGMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILITEMSITEMTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILITEMSSCHEDULE {
        
        private string eTENRField;
        
        private string eINDTField;
        
        private string qUANTITYField;
        
        private string bANFNField;
        
        private string bNFPOField;
        
        private string dELETE_INDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETENR {
            get {
                return this.eTENRField;
            }
            set {
                this.eTENRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANFN {
            get {
                return this.bANFNField;
            }
            set {
                this.bANFNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BNFPO {
            get {
                return this.bNFPOField;
            }
            set {
                this.bNFPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILITEMSACCNTASSIGMENT {
        
        private string zEKKNField;
        
        private string dELETE_INDField;
        
        private string mENGEField;
        
        private string vPROZField;
        
        private string sAKTOField;
        
        private string kOSTLField;
        
        private string aUFNRField;
        
        private string pS_PSP_PNRField;
        
        private string nPLNRField;
        
        private string fISTLField;
        
        private string fIPOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN {
            get {
                return this.zEKKNField;
            }
            set {
                this.zEKKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELETE_IND {
            get {
                return this.dELETE_INDField;
            }
            set {
                this.dELETE_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VPROZ {
            get {
                return this.vPROZField;
            }
            set {
                this.vPROZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAKTO {
            get {
                return this.sAKTOField;
            }
            set {
                this.sAKTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PS_PSP_PNR {
            get {
                return this.pS_PSP_PNRField;
            }
            set {
                this.pS_PSP_PNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NPLNR {
            get {
                return this.nPLNRField;
            }
            set {
                this.nPLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FISTL {
            get {
                return this.fISTLField;
            }
            set {
                this.fISTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIPOS {
            get {
                return this.fIPOSField;
            }
            set {
                this.fIPOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILLIMITS {
        
        private string pACKNOField;
        
        private string sUMLIMITField;
        
        private string sUMNOLIMField;
        
        private string cOMMITMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUMLIMIT {
            get {
                return this.sUMLIMITField;
            }
            set {
                this.sUMLIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUMNOLIM {
            get {
                return this.sUMNOLIMField;
            }
            set {
                this.sUMNOLIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMITMENT {
            get {
                return this.cOMMITMENTField;
            }
            set {
                this.cOMMITMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILSERVICE {
        
        private string pACKNO_EXTField;
        
        private string iNTROW_EXTField;
        
        private string eXTROWField;
        
        private string oUTL_INDField;
        
        private string sUB_PACKNOField;
        
        private string sRVPOSField;
        
        private string dEL_INDField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string pEINHField;
        
        private string bRTWRField;
        
        private string tXZ01Field;
        
        private string pLN_PACKNOField;
        
        private string pLN_INTROWField;
        
        private string dISTRIBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO_EXT {
            get {
                return this.pACKNO_EXTField;
            }
            set {
                this.pACKNO_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW_EXT {
            get {
                return this.iNTROW_EXTField;
            }
            set {
                this.iNTROW_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTROW {
            get {
                return this.eXTROWField;
            }
            set {
                this.eXTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OUTL_IND {
            get {
                return this.oUTL_INDField;
            }
            set {
                this.oUTL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUB_PACKNO {
            get {
                return this.sUB_PACKNOField;
            }
            set {
                this.sUB_PACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SRVPOS {
            get {
                return this.sRVPOSField;
            }
            set {
                this.sRVPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_IND {
            get {
                return this.dEL_INDField;
            }
            set {
                this.dEL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PEINH {
            get {
                return this.pEINHField;
            }
            set {
                this.pEINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTWR {
            get {
                return this.bRTWRField;
            }
            set {
                this.bRTWRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXZ01 {
            get {
                return this.tXZ01Field;
            }
            set {
                this.tXZ01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLN_PACKNO {
            get {
                return this.pLN_PACKNOField;
            }
            set {
                this.pLN_PACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLN_INTROW {
            get {
                return this.pLN_INTROWField;
            }
            set {
                this.pLN_INTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISTRIB {
            get {
                return this.dISTRIBField;
            }
            set {
                this.dISTRIBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:rfq")]
    public partial class dt_rfqpo_responseRFQPO_DETAILPOSRVACCRESSVALUES {
        
        private string pACKNOField;
        
        private string iNTROWField;
        
        private string nUMKNField;
        
        private string zEKKNField;
        
        private string mENGEField;
        
        private string wPROZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKNO {
            get {
                return this.pACKNOField;
            }
            set {
                this.pACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTROW {
            get {
                return this.iNTROWField;
            }
            set {
                this.iNTROWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMKN {
            get {
                return this.nUMKNField;
            }
            set {
                this.nUMKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZEKKN {
            get {
                return this.zEKKNField;
            }
            set {
                this.zEKKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WPROZ {
            get {
                return this.wPROZField;
            }
            set {
                this.wPROZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mi_os_rfqpoCompletedEventHandler(object sender, mi_os_rfqpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mi_os_rfqpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mi_os_rfqpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_rfqpo_responseRFQPO_DETAIL[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_rfqpo_responseRFQPO_DETAIL[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591