//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIHost2host.PR_InqServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mi_os_GetPRBinding", Namespace="urn:pertamina:pr")]
    public partial class mi_os_GetPRService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mi_os_GetPROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mi_os_GetPRService() {
            this.Url = global::APIHost2host.Properties.Settings.Default.APIHost2host_PR_InqServices_mi_os_GetPRService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mi_os_GetPRCompletedEventHandler mi_os_GetPRCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("mt_GetPR_Response", Namespace="urn:pertamina:pr")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("PR_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_GetPR_ResponsePR_DETAILS[] mi_os_GetPR([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:pertamina:pr")] [System.Xml.Serialization.XmlArrayItemAttribute("PR_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] dt_GetPR_RequestPR_DETAILS[] mt_GetPR_Request) {
            object[] results = this.Invoke("mi_os_GetPR", new object[] {
                        mt_GetPR_Request});
            return ((dt_GetPR_ResponsePR_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void mi_os_GetPRAsync(dt_GetPR_RequestPR_DETAILS[] mt_GetPR_Request) {
            this.mi_os_GetPRAsync(mt_GetPR_Request, null);
        }
        
        /// <remarks/>
        public void mi_os_GetPRAsync(dt_GetPR_RequestPR_DETAILS[] mt_GetPR_Request, object userState) {
            if ((this.mi_os_GetPROperationCompleted == null)) {
                this.mi_os_GetPROperationCompleted = new System.Threading.SendOrPostCallback(this.Onmi_os_GetPROperationCompleted);
            }
            this.InvokeAsync("mi_os_GetPR", new object[] {
                        mt_GetPR_Request}, this.mi_os_GetPROperationCompleted, userState);
        }
        
        private void Onmi_os_GetPROperationCompleted(object arg) {
            if ((this.mi_os_GetPRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mi_os_GetPRCompleted(this, new mi_os_GetPRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_RequestPR_DETAILS {
        
        private string cLIENTField;
        
        private string pREQ_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLIENT {
            get {
                return this.cLIENTField;
            }
            set {
                this.cLIENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NO {
            get {
                return this.pREQ_NOField;
            }
            set {
                this.pREQ_NOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILS {
        
        private string pREQ_NOField;
        
        private string pR_TYPEField;
        
        private dt_GetPR_ResponsePR_DETAILSPRHEADERTEXT[] pRHEADERTEXTField;
        
        private dt_GetPR_ResponsePR_DETAILSPRITEM[] pRITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NO {
            get {
                return this.pREQ_NOField;
            }
            set {
                this.pREQ_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PR_TYPE {
            get {
                return this.pR_TYPEField;
            }
            set {
                this.pR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRHEADERTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPR_ResponsePR_DETAILSPRHEADERTEXT[] PRHEADERTEXT {
            get {
                return this.pRHEADERTEXTField;
            }
            set {
                this.pRHEADERTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPR_ResponsePR_DETAILSPRITEM[] PRITEM {
            get {
                return this.pRITEMField;
            }
            set {
                this.pRITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILSPRHEADERTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILSPRITEM {
        
        private string pREQ_ITEMField;
        
        private string mATERIALField;
        
        private string sHORT_TEXTField;
        
        private string qUANTITYField;
        
        private string uNITField;
        
        private string pREQ_PRICEField;
        
        private string cURRENCYField;
        
        private string pRICE_UNITField;
        
        private string pLANTField;
        
        private string pUR_GROUPField;
        
        private string pREQ_DATEField;
        
        private string dELIV_DATEField;
        
        private string pREQ_NAMEField;
        
        private string rEL_INDField;
        
        private string rEL_STATUSField;
        
        private string iTEM_CATField;
        
        private string pURCH_ORGField;
        
        private string aGREEMENTField;
        
        private string aGMT_ITEMField;
        
        private string vALUE_ITEMField;
        
        private string zZMMAUTHNAMEField;
        
        private string zZMMAUTHPOSField;
        
        private dt_GetPR_ResponsePR_DETAILSPRITEMPRITEMTEXT[] pRITEMTEXTField;
        
        private dt_GetPR_ResponsePR_DETAILSPRITEMPRACCOUNT[] pRACCOUNTField;
        
        private dt_GetPR_ResponsePR_DETAILSPRITEMPRADDRDELIVERY[] pRADDRDELIVERYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_ITEM {
            get {
                return this.pREQ_ITEMField;
            }
            set {
                this.pREQ_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_PRICE {
            get {
                return this.pREQ_PRICEField;
            }
            set {
                this.pREQ_PRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE_UNIT {
            get {
                return this.pRICE_UNITField;
            }
            set {
                this.pRICE_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUR_GROUP {
            get {
                return this.pUR_GROUPField;
            }
            set {
                this.pUR_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_DATE {
            get {
                return this.pREQ_DATEField;
            }
            set {
                this.pREQ_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELIV_DATE {
            get {
                return this.dELIV_DATEField;
            }
            set {
                this.dELIV_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREQ_NAME {
            get {
                return this.pREQ_NAMEField;
            }
            set {
                this.pREQ_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REL_IND {
            get {
                return this.rEL_INDField;
            }
            set {
                this.rEL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REL_STATUS {
            get {
                return this.rEL_STATUSField;
            }
            set {
                this.rEL_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_CAT {
            get {
                return this.iTEM_CATField;
            }
            set {
                this.iTEM_CATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PURCH_ORG {
            get {
                return this.pURCH_ORGField;
            }
            set {
                this.pURCH_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGREEMENT {
            get {
                return this.aGREEMENTField;
            }
            set {
                this.aGREEMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGMT_ITEM {
            get {
                return this.aGMT_ITEMField;
            }
            set {
                this.aGMT_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALUE_ITEM {
            get {
                return this.vALUE_ITEMField;
            }
            set {
                this.vALUE_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHNAME {
            get {
                return this.zZMMAUTHNAMEField;
            }
            set {
                this.zZMMAUTHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMMAUTHPOS {
            get {
                return this.zZMMAUTHPOSField;
            }
            set {
                this.zZMMAUTHPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRITEMTEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPR_ResponsePR_DETAILSPRITEMPRITEMTEXT[] PRITEMTEXT {
            get {
                return this.pRITEMTEXTField;
            }
            set {
                this.pRITEMTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPR_ResponsePR_DETAILSPRITEMPRACCOUNT[] PRACCOUNT {
            get {
                return this.pRACCOUNTField;
            }
            set {
                this.pRACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRADDRDELIVERY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_GetPR_ResponsePR_DETAILSPRITEMPRADDRDELIVERY[] PRADDRDELIVERY {
            get {
                return this.pRADDRDELIVERYField;
            }
            set {
                this.pRADDRDELIVERYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILSPRITEMPRITEMTEXT {
        
        private string tEXT_IDField;
        
        private string tEXT_FORMField;
        
        private string tEXT_LINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_ID {
            get {
                return this.tEXT_IDField;
            }
            set {
                this.tEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_FORM {
            get {
                return this.tEXT_FORMField;
            }
            set {
                this.tEXT_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXT_LINE {
            get {
                return this.tEXT_LINEField;
            }
            set {
                this.tEXT_LINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILSPRITEMPRACCOUNT {
        
        private string gL_ACCOUNTField;
        
        private string cOSTCENTERField;
        
        private string oRDERIDField;
        
        private string wBS_ELEMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GL_ACCOUNT {
            get {
                return this.gL_ACCOUNTField;
            }
            set {
                this.gL_ACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COSTCENTER {
            get {
                return this.cOSTCENTERField;
            }
            set {
                this.cOSTCENTERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDERID {
            get {
                return this.oRDERIDField;
            }
            set {
                this.oRDERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WBS_ELEMENT {
            get {
                return this.wBS_ELEMENTField;
            }
            set {
                this.wBS_ELEMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:pr")]
    public partial class dt_GetPR_ResponsePR_DETAILSPRITEMPRADDRDELIVERY {
        
        private string nAMEField;
        
        private string sTREETField;
        
        private string hOUSE_NOField;
        
        private string cITYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NO {
            get {
                return this.hOUSE_NOField;
            }
            set {
                this.hOUSE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mi_os_GetPRCompletedEventHandler(object sender, mi_os_GetPRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mi_os_GetPRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mi_os_GetPRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_GetPR_ResponsePR_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_GetPR_ResponsePR_DETAILS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591