//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace APIHost2host.GR_Services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mi_os_gr_pipsBinding", Namespace="urn:pertamina:gr")]
    public partial class mi_os_gr_pipsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mi_os_gr_pipsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mi_os_gr_pipsService() {
            this.Url = global::APIHost2host.Properties.Settings.Default.APIHost2host_GR_Services_mi_os_gr_pipsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mi_os_gr_pipsCompletedEventHandler mi_os_gr_pipsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("mt_gr_response", Namespace="urn:pertamina:gr")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GR_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dt_gr_responseGR_DETAILS[] mi_os_gr_pips([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:pertamina:gr")] [System.Xml.Serialization.XmlArrayItemAttribute("GR_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] dt_gr_requestGR_DETAILS[] mt_gr_request) {
            object[] results = this.Invoke("mi_os_gr_pips", new object[] {
                        mt_gr_request});
            return ((dt_gr_responseGR_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void mi_os_gr_pipsAsync(dt_gr_requestGR_DETAILS[] mt_gr_request) {
            this.mi_os_gr_pipsAsync(mt_gr_request, null);
        }
        
        /// <remarks/>
        public void mi_os_gr_pipsAsync(dt_gr_requestGR_DETAILS[] mt_gr_request, object userState) {
            if ((this.mi_os_gr_pipsOperationCompleted == null)) {
                this.mi_os_gr_pipsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmi_os_gr_pipsOperationCompleted);
            }
            this.InvokeAsync("mi_os_gr_pips", new object[] {
                        mt_gr_request}, this.mi_os_gr_pipsOperationCompleted, userState);
        }
        
        private void Onmi_os_gr_pipsOperationCompleted(object arg) {
            if ((this.mi_os_gr_pipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mi_os_gr_pipsCompleted(this, new mi_os_gr_pipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:gr")]
    public partial class dt_gr_requestGR_DETAILS {
        
        private string mANDTField;
        
        private string oPTYPEField;
        
        private string mBLNR_EXTField;
        
        private string mBLNRField;
        
        private string mJAHRField;
        
        private string tESTRUNField;
        
        private string bLDATField;
        
        private string bUDATField;
        
        private string lFSNRField;
        
        private string fRBNRField;
        
        private string bKTXTField;
        
        private string zDELField;
        
        private string tGLDELIVERField;
        
        private string zMULTIPLIERField;
        
        private string zJUSTIFIKASIField;
        
        private string tKDNField;
        
        private dt_gr_requestGR_DETAILSITEMS[] iTEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPTYPE {
            get {
                return this.oPTYPEField;
            }
            set {
                this.oPTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNR_EXT {
            get {
                return this.mBLNR_EXTField;
            }
            set {
                this.mBLNR_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MJAHR {
            get {
                return this.mJAHRField;
            }
            set {
                this.mJAHRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TESTRUN {
            get {
                return this.tESTRUNField;
            }
            set {
                this.tESTRUNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LFSNR {
            get {
                return this.lFSNRField;
            }
            set {
                this.lFSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FRBNR {
            get {
                return this.fRBNRField;
            }
            set {
                this.fRBNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZDEL {
            get {
                return this.zDELField;
            }
            set {
                this.zDELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TGLDELIVER {
            get {
                return this.tGLDELIVERField;
            }
            set {
                this.tGLDELIVERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZMULTIPLIER {
            get {
                return this.zMULTIPLIERField;
            }
            set {
                this.zMULTIPLIERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJUSTIFIKASI {
            get {
                return this.zJUSTIFIKASIField;
            }
            set {
                this.zJUSTIFIKASIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TKDN {
            get {
                return this.tKDNField;
            }
            set {
                this.tKDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_gr_requestGR_DETAILSITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:gr")]
    public partial class dt_gr_requestGR_DETAILSITEMS {
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string eRFMGField;
        
        private string eRFMEField;
        
        private string lSMNGField;
        
        private string bWARTField;
        
        private string iNSMKField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private string wEMPFField;
        
        private string aBLADField;
        
        private string sGTXTField;
        
        private string iTEMINDICATORField;
        
        private string eLIKZField;
        
        private string pRCTRField;
        
        private string kOSTLField;
        
        private string rEF_DOC_YRField;
        
        private string rEF_DOCField;
        
        private string rEF_DOC_ITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERFMG {
            get {
                return this.eRFMGField;
            }
            set {
                this.eRFMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERFME {
            get {
                return this.eRFMEField;
            }
            set {
                this.eRFMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LSMNG {
            get {
                return this.lSMNGField;
            }
            set {
                this.lSMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INSMK {
            get {
                return this.iNSMKField;
            }
            set {
                this.iNSMKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEMPF {
            get {
                return this.wEMPFField;
            }
            set {
                this.wEMPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ABLAD {
            get {
                return this.aBLADField;
            }
            set {
                this.aBLADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SGTXT {
            get {
                return this.sGTXTField;
            }
            set {
                this.sGTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMINDICATOR {
            get {
                return this.iTEMINDICATORField;
            }
            set {
                this.iTEMINDICATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ELIKZ {
            get {
                return this.eLIKZField;
            }
            set {
                this.eLIKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRCTR {
            get {
                return this.pRCTRField;
            }
            set {
                this.pRCTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC_YR {
            get {
                return this.rEF_DOC_YRField;
            }
            set {
                this.rEF_DOC_YRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC {
            get {
                return this.rEF_DOCField;
            }
            set {
                this.rEF_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC_IT {
            get {
                return this.rEF_DOC_ITField;
            }
            set {
                this.rEF_DOC_ITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:gr")]
    public partial class dt_gr_responseGR_DETAILS {
        
        private string mANDTField;
        
        private string mBLNR_EXTField;
        
        private string mBLNRField;
        
        private string mJAHRField;
        
        private string cOMM_FLAGField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private dt_gr_responseGR_DETAILSMSG_DETAILS[] mSG_DETAILSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNR_EXT {
            get {
                return this.mBLNR_EXTField;
            }
            set {
                this.mBLNR_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNR {
            get {
                return this.mBLNRField;
            }
            set {
                this.mBLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MJAHR {
            get {
                return this.mJAHRField;
            }
            set {
                this.mJAHRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMM_FLAG {
            get {
                return this.cOMM_FLAGField;
            }
            set {
                this.cOMM_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSG_DETAILS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_gr_responseGR_DETAILSMSG_DETAILS[] MSG_DETAILS {
            get {
                return this.mSG_DETAILSField;
            }
            set {
                this.mSG_DETAILSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:gr")]
    public partial class dt_gr_responseGR_DETAILSMSG_DETAILS {
        
        private string tYPEField;
        
        private string mSG_DETField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSG_DET {
            get {
                return this.mSG_DETField;
            }
            set {
                this.mSG_DETField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mi_os_gr_pipsCompletedEventHandler(object sender, mi_os_gr_pipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mi_os_gr_pipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mi_os_gr_pipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dt_gr_responseGR_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dt_gr_responseGR_DETAILS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591